// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhkxnbmschisdkiubupt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRoa3huYm1zY2hpc2RraXVidXB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI3MTkyMTMsImV4cCI6MjA3ODI5NTIxM30.2MpIgFAN6IFfuz2lLqzWzspFerOmwyANziugbO6kACk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});